### ISSUE TITLE
Anki fails to open following installation

### ISSUE THREAD

**Issue by n2taylor** [glfharris/ankidown#12]
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-04-16 11:15:20
Add-ons possibly involved: ⁨Ankidown - The advanced importer for Anki⁩

```
/Users/nick/Library/Application Support/Anki2/addons21/38786043/importer.py:127: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.bufferIndex is 0:
/Users/nick/Library/Application Support/Anki2/addons21/38786043/template.py:85: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if selection is 0:
```

**Comment by n2taylor** [comment]
Seems like you already fixed this. However the current version on AnkiWeb does not have the fix, so whenever this fix could be pushed out, it would be much appreciated

https://github.com/glfharris/ankidown/commit/276515ec8e5a563d22054b9bdaa8ab010e2cdeda

**Comment by glfharris** [comment]
Just done it now! Thanks for the reminder!
