### ISSUE TITLE
Make the install process easier

### ISSUE THREAD

**Issue by jay-pee** [glfharris/ankidown#2]
I had to overcome the problem that I have to build the import/export UI.
Maybe would be great to include the *forms* folder in the git repo.

I am on windows and didn't had `make` and `pyqt5-tools` installed.
It's a little cumbersome to get the plugin to run with this issue.

Also short install guide would be great in the `readme.md` file.

Should I do a pull request for this?

**Comment by glfharris** [comment]
The intended route for installation is going to be through ankiweb, just need to get around to writing documentation before uploading an initial version.
As far as dev dependencies, I don't really have much experience trying to build things on windows, so not sure what the ideal route would be. I'm a little wary of committing the forms folder as there's the potential to accidentally commit out of date forms which would just be a nuisance.

**Comment by jay-pee** [comment]
Maybe a continuous integration (CI) process that builds the forms when committing. But I also don't know exactly how to implement this. I think when you find the time to upload the plugin to ankiweb then it should be fine.

**Comment by glfharris** [comment]
Have finally got round to uploading a version to Ankiweb - https://ankiweb.net/shared/info/38786043
