### ISSUE TITLE
Imports only notes in the standard deck

### ISSUE THREAD

**Issue by jay-pee** [glfharris/ankidown#3]
Doesn't matter what deck I select in the importer GUI, it always adds the notes to the standard deck.

**Comment by glfharris** [comment]
Could I just get you to clarify what you mean by standard deck? So far the deck selection widget has been working for me.

**Comment by jay-pee** [comment]
So I have a Deck "test" like so:

![Capture3](https://user-images.githubusercontent.com/9380980/60737499-4df12380-9f5b-11e9-8c33-2fd651525f84.PNG)

Then I add a Note like this:

![Capture4](https://user-images.githubusercontent.com/9380980/60737512-58abb880-9f5b-11e9-899c-0fa0332eb59b.PNG)

And then the note is not going into the test deck but in the default deck. (In German maybe called Standard):

![Capture2](https://user-images.githubusercontent.com/9380980/60737556-81cc4900-9f5b-11e9-9736-cacb016b8ce5.PNG)

**Comment by jay-pee** [comment]
So I have a deck called "test":

![Capture3](https://user-images.githubusercontent.com/9380980/60737616-bcce7c80-9f5b-11e9-81c1-6ef339009dc1.PNG)

Then I try to add a note to the deck like this:

![Capture4](https://user-images.githubusercontent.com/9380980/60737632-cce65c00-9f5b-11e9-8d12-b30153265bd2.PNG)

And then the note is added to the default deck. (In German maybe called Standard).

![Capture2](https://user-images.githubusercontent.com/9380980/60737690-f1423880-9f5b-11e9-832e-1d37dfd780aa.PNG)

**Comment by glfharris** [comment]
Found what the problem was, this is fixed in the latest version. Thanks!
